sudo: false
language: node_js
node_js:
- '0.10'
addons:
  firefox: "35.0"
  apt:
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - build-essential
      - g++
before_install:
- npm install -g grunt-cli bower
install:
- travis_retry npm install
- bower install
- ./node_modules/.bin/webdriver-manager update --standalone
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- bower install
- grunt connect:keepalive &
- nohup bash -c "./node_modules/.bin/webdriver-manager start 2>&1 &"
- sleep 5 # wait for selenium server to actually come up
script:
- grunt
- grunt test:full
- ./node_modules/.bin/protractor
- grunt karma:minified
after_success:
- grunt coveralls
- ./utils/visual-regression/clone.sh
- ./utils/visual-regression/test.sh
- ./utils/visual-regression/push.sh
- ./utils/visual-regression/pr.sh
env:
  global:
  - secure: S6sdJYgRgdlwGR14hTH8zYSkF+bvjKiCEpsxHdiQLJL6T9hgByObdkpiOiKnt4Y2uuAfY0JUKsM/TG4apN22mH0R+xafmYx7+uMMEcBDB5EWJtohdaCkg/GgRFRTs5FkkJKBS+lIObDjjRyeGFh2uGjyXTTgtp+m1FIFj3mOQlw=
  - secure: jRx4ZPL0X0+LbAhPL9gYcTePHLtOhuiN2hamfbKCWL9ASvNhHTGeU4jZ/k2pDdaiNC2Hr4ZUglJPqGQ3VkrzKU9WJYg2/SpBpO/ERe39d2wE/qyx/AOYXMqzb07YGi2E4CnmAE5r0DIqMC+VIzPzqfz1mxKOq8bTcemT4z3xKkU=
notifications:
  email: false
  slack:
    secure: IyMKdUkXFeSPf0oTgHuvXGhJjJfiZTUbe/WUDyoOHgCuN/sempE0zHphwF/dEOcnGNsi7quGTTlv2AUq9ADVe4yeVy9YuxJqnNBeNMXViA+pBVX4A8W7UxaQclM+gWFteoK52EtjUNZNuZ5XOKFo04QtGxhaN4Qddd6geSR+fPE=
